#include "remote_serial_backend.h"

#include <QThread>
#include <QWebSocket>
#include <utility>
#include "qtrohelper.hpp"
#include "rep_serial_port_actions_replica.h"

RemoteSerialBackend::RemoteSerialBackend(QString peerAddress, QString password,
                                         QWebSocket *externalSocket, QObject *parent)
    : QObject{parent}, peerAddress(std::move(peerAddress)), password(std::move(password))
{
    if (externalSocket && externalSocket->thread() != thread())
    {
        emit LOG_W("RemoteSerialBackend: external websocket has foreign thread "
                   "affinity, creating own socket instead",
                   true, true);
        externalSocket = nullptr;
    }
    webSocket = externalSocket ? externalSocket
                               : new QWebSocket("", QWebSocketProtocol::VersionLatest, this);
    socket = new WebSocketIoDevice(webSocket, webSocket);
    startRemote();
}

RemoteSerialBackend::~RemoteSerialBackend()
{
}

void RemoteSerialBackend::waitForSource()
{
    while (!serial_remote->waitForSource(10000))
    {
        sendAutoDiscoveryMessage();
        QThread::msleep(50);
        emit LOG_D("RemoteSerialBackend: Waiting for remote peer...", true, true);
    }
}

void RemoteSerialBackend::startRemote()
{
    if (peerAddress.startsWith("local:"))
    {
        startLocal();
    }
    else
    {
        startOverNetwork();
    }
    QObject::connect(serial_remote, &SerialPortActionsRemoteReplica::stateChanged,
                     this, &RemoteSerialBackend::serialRemoteStateChanged);
}

void RemoteSerialBackend::startOverNetwork()
{
    QSslConfiguration sslConfiguration;
    sslConfiguration.setPeerVerifyMode(QSslSocket::VerifyNone);
    webSocket->setSslConfiguration(sslConfiguration);
    // Start node when Web Socket will be up
    QObject::connect(webSocket, &QWebSocket::connected, this, &RemoteSerialBackend::websocket_connected);
    node.setHeartbeatInterval(heartbeatInterval);
    QObject::connect(webSocket, QOverload<QAbstractSocket::SocketError>::of(&QWebSocket::error),
                     this, [=](QAbstractSocket::SocketError error)
                     { emit LOG_D(QString(this->metaObject()->className()) + " startOverNetwork QWebSocket error: " + QMetaEnum::fromType<QAbstractSocket::SocketError>().valueToKey(error), true, true); });
    // WebSocket over SSL
    QUrl url("wss://" + peerAddress);
    url.setPath(wssPath);
    QNetworkRequest req;
    req.setRawHeader(webSocketPasswordHeader.toUtf8(), password.toUtf8());
    req.setUrl(url);
    webSocket->open(req);

    // Connect to source published with name
    // Class SerialPortActionsRemoteReplica is autogenerated from serial_port_actions.rep
    serial_remote = node.acquire<SerialPortActionsRemoteReplica>(remoteObjectName);
    // Don't wait for replication here, it should be done from outside
}

void RemoteSerialBackend::startLocal()
{
    node.connectToNode(QUrl(peerAddress));
    serial_remote = node.acquire<SerialPortActionsRemoteReplica>(remoteObjectName);
}

void RemoteSerialBackend::sendAutoDiscoveryMessage()
{
    if (webSocket->isValid())
    {
        webSocket->sendTextMessage(autodiscoveryMessage);
    }
}

void RemoteSerialBackend::websocket_connected()
{
    // Run client node after socket is up
    node.addClientSideConnection(socket);
    sendAutoDiscoveryMessage();
}

void RemoteSerialBackend::serialRemoteStateChanged(QRemoteObjectReplica::State state, QRemoteObjectReplica::State oldState)
{
    emit stateChanged(state, oldState);
    if (state == QRemoteObjectReplica::Valid)
    {
        emit LOG_D("RemoteSerialBackend remote connection established", true, true);
    }
    else if (oldState == QRemoteObjectReplica::Valid)
    {
        emit LOG_D("RemoteSerialBackend remote connection lost", true, true);
    }
}

// -- config get/set pairs (44) ------------------------------------------

bool RemoteSerialBackend::get_serialPortAvailable()
{
    return qtrohelper::slot_sync(serial_remote->get_serialPortAvailable());
}
bool RemoteSerialBackend::set_serialPortAvailable(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_serialPortAvailable(value));
}
bool RemoteSerialBackend::get_setRequestToSend()
{
    return qtrohelper::slot_sync(serial_remote->get_setRequestToSend());
}
bool RemoteSerialBackend::set_setRequestToSend(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_setRequestToSend(value));
}
bool RemoteSerialBackend::get_setDataTerminalReady()
{
    return qtrohelper::slot_sync(serial_remote->get_setDataTerminalReady());
}
bool RemoteSerialBackend::set_setDataTerminalReady(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_setDataTerminalReady(value));
}

bool RemoteSerialBackend::get_add_ssm_header()
{
    return qtrohelper::slot_sync(serial_remote->get_add_ssm_header());
}
bool RemoteSerialBackend::set_add_ssm_header(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_add_ssm_header(value));
}

bool RemoteSerialBackend::get_add_iso9141_header()
{
    return qtrohelper::slot_sync(serial_remote->get_add_iso9141_header());
}
bool RemoteSerialBackend::set_add_iso9141_header(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_add_iso9141_header(value));
}

bool RemoteSerialBackend::get_add_iso14230_header()
{
    return qtrohelper::slot_sync(serial_remote->get_add_iso14230_header());
}
bool RemoteSerialBackend::set_add_iso14230_header(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_add_iso14230_header(value));
}
bool RemoteSerialBackend::get_is_iso14230_connection()
{
    return qtrohelper::slot_sync(serial_remote->get_is_iso14230_connection());
}
bool RemoteSerialBackend::set_is_iso14230_connection(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_is_iso14230_connection(value));
}
bool RemoteSerialBackend::get_is_can_connection()
{
    return qtrohelper::slot_sync(serial_remote->get_is_can_connection());
}
bool RemoteSerialBackend::set_is_can_connection(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_is_can_connection(value));
}
bool RemoteSerialBackend::get_is_iso15765_connection()
{
    return qtrohelper::slot_sync(serial_remote->get_is_iso15765_connection());
}
bool RemoteSerialBackend::set_is_iso15765_connection(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_is_iso15765_connection(value));
}
bool RemoteSerialBackend::get_is_29_bit_id()
{
    return qtrohelper::slot_sync(serial_remote->get_is_29_bit_id());
}
bool RemoteSerialBackend::set_is_29_bit_id(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_is_29_bit_id(value));
}

bool RemoteSerialBackend::get_use_openport2_adapter()
{
    return qtrohelper::slot_sync(serial_remote->get_use_openport2_adapter());
}
bool RemoteSerialBackend::set_use_openport2_adapter(bool value)
{
    return qtrohelper::slot_sync(serial_remote->set_use_openport2_adapter(value));
}

int RemoteSerialBackend::get_requestToSendEnabled()
{
    return qtrohelper::slot_sync(serial_remote->get_requestToSendEnabled());
}
bool RemoteSerialBackend::set_requestToSendEnabled(int value)
{
    return qtrohelper::slot_sync(serial_remote->set_requestToSendEnabled(value));
}
int RemoteSerialBackend::get_requestToSendDisabled()
{
    return qtrohelper::slot_sync(serial_remote->get_requestToSendDisabled());
}
bool RemoteSerialBackend::set_requestToSendDisabled(int value)
{
    return qtrohelper::slot_sync(serial_remote->set_requestToSendDisabled(value));
}
int RemoteSerialBackend::get_dataTerminalEnabled()
{
    return qtrohelper::slot_sync(serial_remote->get_dataTerminalEnabled());
}
bool RemoteSerialBackend::set_dataTerminalEnabled(int value)
{
    return qtrohelper::slot_sync(serial_remote->set_dataTerminalEnabled(value));
}
int RemoteSerialBackend::get_dataTerminalDisabled()
{
    return qtrohelper::slot_sync(serial_remote->get_dataTerminalDisabled());
}
bool RemoteSerialBackend::set_dataTerminalDisabled(int value)
{
    return qtrohelper::slot_sync(serial_remote->set_dataTerminalDisabled(value));
}

uint8_t RemoteSerialBackend::get_kline_startbyte()
{
    return qtrohelper::slot_sync(serial_remote->get_kline_startbyte());
}
bool RemoteSerialBackend::set_kline_startbyte(uint8_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_kline_startbyte(value));
}
uint8_t RemoteSerialBackend::get_kline_tester_id()
{
    return qtrohelper::slot_sync(serial_remote->get_kline_tester_id());
}
bool RemoteSerialBackend::set_kline_tester_id(uint8_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_kline_tester_id(value));
}
uint8_t RemoteSerialBackend::get_kline_target_id()
{
    return qtrohelper::slot_sync(serial_remote->get_kline_target_id());
}
bool RemoteSerialBackend::set_kline_target_id(uint8_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_kline_target_id(value));
}

QByteArray RemoteSerialBackend::get_ssm_receive_header_start()
{
    return qtrohelper::slot_sync(serial_remote->get_ssm_receive_header_start());
}
bool RemoteSerialBackend::set_ssm_receive_header_start(QByteArray value)
{
    return qtrohelper::slot_sync(serial_remote->set_ssm_receive_header_start(value));
}

QStringList RemoteSerialBackend::get_serial_port_list()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_list());
}
bool RemoteSerialBackend::set_serial_port_list(QStringList value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_list(value));
}
QString RemoteSerialBackend::get_openedSerialPort()
{
    return qtrohelper::slot_sync(serial_remote->get_openedSerialPort());
}
bool RemoteSerialBackend::set_openedSerialPort(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_openedSerialPort(value));
}
QString RemoteSerialBackend::get_subaru_02_16bit_bootloader_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_02_16bit_bootloader_baudrate());
}
bool RemoteSerialBackend::set_subaru_02_16bit_bootloader_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_02_16bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_04_16bit_bootloader_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_04_16bit_bootloader_baudrate());
}
bool RemoteSerialBackend::set_subaru_04_16bit_bootloader_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_04_16bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_02_32bit_bootloader_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_02_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::set_subaru_02_32bit_bootloader_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_02_32bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_04_32bit_bootloader_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_04_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::set_subaru_04_32bit_bootloader_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_04_32bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_05_32bit_bootloader_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_05_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::set_subaru_05_32bit_bootloader_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_05_32bit_bootloader_baudrate(value));
}

QString RemoteSerialBackend::get_subaru_02_16bit_kernel_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_02_16bit_kernel_baudrate());
}
bool RemoteSerialBackend::set_subaru_02_16bit_kernel_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_02_16bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_04_16bit_kernel_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_04_16bit_kernel_baudrate());
}
bool RemoteSerialBackend::set_subaru_04_16bit_kernel_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_04_16bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_02_32bit_kernel_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_02_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::set_subaru_02_32bit_kernel_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_02_32bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_04_32bit_kernel_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_04_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::set_subaru_04_32bit_kernel_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_04_32bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::get_subaru_05_32bit_kernel_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_subaru_05_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::set_subaru_05_32bit_kernel_baudrate(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_subaru_05_32bit_kernel_baudrate(value));
}

QString RemoteSerialBackend::get_can_speed()
{
    return qtrohelper::slot_sync(serial_remote->get_can_speed());
}
bool RemoteSerialBackend::set_can_speed(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_can_speed(value));
}
uint8_t RemoteSerialBackend::get_serial_port_parity()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_parity());
}
bool RemoteSerialBackend::set_serial_port_parity(uint8_t parity)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_parity(parity));
}
QString RemoteSerialBackend::get_serial_port_baudrate()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_baudrate());
}
bool RemoteSerialBackend::set_serial_port_baudrate(QString value)
{
    emit LOG_D("Setting serialport baudrate in RemoteSerialBackend", true, true);
    return qtrohelper::slot_sync(serial_remote->set_serial_port_baudrate(value));
}
QString RemoteSerialBackend::get_serial_port_linux()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_linux());
}
bool RemoteSerialBackend::set_serial_port_linux(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_linux(value));
}
QString RemoteSerialBackend::get_serial_port_windows()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_windows());
}
bool RemoteSerialBackend::set_serial_port_windows(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_windows(value));
}
QString RemoteSerialBackend::get_serial_port()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port());
}
bool RemoteSerialBackend::set_serial_port(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port(value));
}
QString RemoteSerialBackend::get_serial_port_prefix()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_prefix());
}
bool RemoteSerialBackend::set_serial_port_prefix(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_prefix(value));
}
QString RemoteSerialBackend::get_serial_port_prefix_linux()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_prefix_linux());
}
bool RemoteSerialBackend::set_serial_port_prefix_linux(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_prefix_linux(value));
}
QString RemoteSerialBackend::get_serial_port_prefix_win()
{
    return qtrohelper::slot_sync(serial_remote->get_serial_port_prefix_win());
}
bool RemoteSerialBackend::set_serial_port_prefix_win(QString value)
{
    return qtrohelper::slot_sync(serial_remote->set_serial_port_prefix_win(value));
}

uint32_t RemoteSerialBackend::get_can_source_address()
{
    return qtrohelper::slot_sync(serial_remote->get_can_source_address());
}
bool RemoteSerialBackend::set_can_source_address(uint32_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_can_source_address(value));
}
uint32_t RemoteSerialBackend::get_can_destination_address()
{
    return qtrohelper::slot_sync(serial_remote->get_can_destination_address());
}
bool RemoteSerialBackend::set_can_destination_address(uint32_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_can_destination_address(value));
}
uint32_t RemoteSerialBackend::get_iso15765_source_address()
{
    return qtrohelper::slot_sync(serial_remote->get_iso15765_source_address());
}
bool RemoteSerialBackend::set_iso15765_source_address(uint32_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_iso15765_source_address(value));
}
uint32_t RemoteSerialBackend::get_iso15765_destination_address()
{
    return qtrohelper::slot_sync(serial_remote->get_iso15765_destination_address());
}
bool RemoteSerialBackend::set_iso15765_destination_address(uint32_t value)
{
    return qtrohelper::slot_sync(serial_remote->set_iso15765_destination_address(value));
}

// -- operations -----------------------------------------------------------

bool RemoteSerialBackend::is_serial_port_open()
{
    return qtrohelper::slot_sync(serial_remote->is_serial_port_open());
}

int RemoteSerialBackend::change_port_speed(QString portSpeed)
{
    return qtrohelper::slot_sync(serial_remote->change_port_speed(portSpeed));
}

// NOTE: pinned quirk, preserved verbatim from the old facade (serial_port_actions.cpp
// set_kline_timings, lines 885-891): the remote branch never forwarded this call to
// serial_remote at all (only the direct branch did anything), and the facade always
// returned STATUS_SUCCESS (true) regardless. Not a bug this task is chartered to fix.
bool RemoteSerialBackend::set_kline_timings(uint32_t parameter, int value)
{
    Q_UNUSED(parameter);
    Q_UNUSED(value);
    return true;
}

int RemoteSerialBackend::set_j2534_ioctl(uint32_t parameter, int value)
{
    return qtrohelper::slot_sync(serial_remote->set_j2534_ioctl(parameter, value));
}

QByteArray RemoteSerialBackend::five_baud_init(QByteArray output)
{
    return qtrohelper::slot_sync(serial_remote->five_baud_init(output));
}

int RemoteSerialBackend::fast_init(QByteArray output)
{
    return qtrohelper::slot_sync(serial_remote->fast_init(output));
}

int RemoteSerialBackend::set_lec_lines(int lec1, int lec2)
{
    return qtrohelper::slot_sync(serial_remote->set_lec_lines(lec1, lec2));
}

int RemoteSerialBackend::pulse_lec_1_line(int timeout)
{
    return qtrohelper::slot_sync(serial_remote->pulse_lec_1_line(timeout));
}

int RemoteSerialBackend::pulse_lec_2_line(int timeout)
{
    return qtrohelper::slot_sync(serial_remote->pulse_lec_2_line(timeout));
}

void RemoteSerialBackend::reset_connection()
{
    qtrohelper::slot_sync(serial_remote->reset_connection()); // bool result discarded
}

// NOTE: pinned quirk, preserved verbatim from the old facade (serial_port_actions.cpp
// read_serial_obd_data, lines 1005-1016): the remote branch was never populated in the
// original if/else — only the isDirectConnection() branch called through and logged a
// response; the remote path fell through and returned a default-constructed (empty)
// QByteArray without ever calling serial_remote. The .rep does expose this slot
// (SerialPortActionsRemoteReplica::read_serial_obd_data), so this looks like an
// omission in the old code rather than an intentional no-op, but this task's mandate
// is a mechanical, behavior-preserving move -- not a bugfix -- so the omission is
// pinned here rather than "fixed" by wiring in the call.
QByteArray RemoteSerialBackend::read_serial_obd_data(uint16_t timeout)
{
    Q_UNUSED(timeout);
    return QByteArray();
}

QByteArray RemoteSerialBackend::read_serial_data(uint16_t timeout)
{
    return qtrohelper::slot_sync(serial_remote->read_serial_data(timeout));
}

QByteArray RemoteSerialBackend::write_serial_data(QByteArray output)
{
    return qtrohelper::slot_sync(serial_remote->write_serial_data(output));
}

QByteArray RemoteSerialBackend::write_serial_data_echo_check(QByteArray output)
{
    return qtrohelper::slot_sync(serial_remote->write_serial_data_echo_check(output));
}

// NOTE: pinned quirk, preserved from the old facade (serial_port_actions.cpp
// get_is_tx_done, lines 1069-1075): the remote branch was commented out, so the old
// non-void function fell off the end on the remote path -- undefined behavior. There
// is no safe value to "recover" from the original, so this pins a safe default: report
// tx done so callers relying on this to gate further sends don't spin/deadlock.
bool RemoteSerialBackend::get_is_tx_done()
{
    return true;
}

int RemoteSerialBackend::clear_rx_buffer()
{
    return qtrohelper::slot_sync(serial_remote->clear_rx_buffer());
}

int RemoteSerialBackend::clear_tx_buffer()
{
    return qtrohelper::slot_sync(serial_remote->clear_tx_buffer());
}

int RemoteSerialBackend::send_periodic_j2534_data(QByteArray output, int timeout)
{
    return qtrohelper::slot_sync(serial_remote->send_periodic_j2534_data(output, timeout));
}

int RemoteSerialBackend::stop_periodic_j2534_data()
{
    return qtrohelper::slot_sync(serial_remote->stop_periodic_j2534_data());
}

QStringList RemoteSerialBackend::check_serial_ports()
{
    return qtrohelper::slot_sync(serial_remote->check_serial_ports());
}

QString RemoteSerialBackend::open_serial_port()
{
    return qtrohelper::slot_sync(serial_remote->open_serial_port());
}

unsigned long RemoteSerialBackend::read_vbatt()
{
    return qtrohelper::slot_sync(serial_remote->read_vbatt());
}
