sonar.projectKey=RcusStackwalker_FastECU
sonar.organization=rcusstackwalker
sonar.projectName=FastECU
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.tests=tests

sonar.cfamily.build-wrapper-output=bw-output
sonar.cfamily.llvm-cov.reportPath=coverage/llvm-cov.report

sonar.exclusions=\
  tests/**,\
  FastECU.app/**,\
  kernels/**,\
  bw-output/**,\
  coverage/**,\
  dist/**,\
  .tmp/**,\
  **/build/**,\
  **/*build-*/**,\
  **/*.o,\
  **/*.a,\
  **/*.so,\
  **/*.dll,\
  **/*.dylib,\
  **/Makefile*,\
  **/.qmake.stash,\
  **/moc_*,\
  **/ui_*,\
  **/qrc_*,\
  **/rep_*_replica.h

sonar.coverage.exclusions=\
  tests/**,\
  hexedit/**,\
  **/moc_*,\
  **/ui_*,\
  **/qrc_*,\
  **/rep_*_replica.h
