load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gtest_targets.bzl", "fastecu_portable_gtest")

package(default_visibility = ["//bazel/layers:algorithms_and_above"])

cc_library(
    name = "menu",
    srcs = ["menu_command.cpp"],
    hdrs = ["menu_command.h"],
)

fastecu_portable_gtest(
    name = "menu_command_test",
    srcs = ["menu_command_test.cpp"],
    deps = [
        ":menu",
        "@googletest//:gtest",
    ],
)
