load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gtest_targets.bzl", "fastecu_portable_gtest")

package(default_visibility = ["//bazel/layers:algorithms_and_above"])

cc_library(
    name = "expression",
    srcs = ["expression_evaluator.cpp"],
    hdrs = ["expression_evaluator.h"],
)

fastecu_portable_gtest(
    name = "expression_evaluator_test",
    srcs = ["expression_evaluator_test.cpp"],
    deps = [
        ":expression",
        "@googletest//:gtest",
    ],
)
