load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gtest_targets.bzl", "fastecu_portable_gtest")

package(default_visibility = ["//bazel/layers:algorithms_and_above"])

cc_library(
    name = "expression",
    srcs = ["expression.cpp"],
    hdrs = ["expression.h"],
)

fastecu_portable_gtest(
    name = "expression_test",
    srcs = ["expression_test.cpp"],
    deps = [
        ":expression",
        "@googletest//:gtest",
    ],
)
