# gazelle:resolve cc src/platform/desktop/common/serial/websocketiodevice.h //src/platform/desktop/common/serial:websocket_io
# gazelle:resolve cc src/platform/desktop/common/serial/qtrohelper.hpp //src/platform/desktop/common/serial:websocket_io
# gazelle:resolve cc rep_remote_utility_replica.h :remote_utility_replicas
# gazelle:map_kind cc_library qt_cc_library //bazel:qt_targets.bzl
load("//bazel:qt_remote_objects.bzl", "qt_replica_library")
load("//bazel:qt_targets.bzl", "QT_DEPS", "qt_cc_library")

package(default_visibility = ["//bazel/layers:platform_and_composition_root"])

qt_replica_library(
    name = "remote_utility_replicas",
    reps = ["remote_utility.rep"],
    deps = QT_DEPS,
)

qt_cc_library(
    name = "remote_utility",
    srcs = ["remote_utility.cpp"],
    hdrs = ["remote_utility.h"],
    implementation_deps = ["//src/platform/desktop/common/remote_utility:remote_utility_replicas"],
    deps = [
        "//bazel/qt:core",
        "//bazel/qt:remote_objects",
        "//src/platform/desktop/common/serial:websocket_io",
    ],
)
