load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//src:__subpackages__"])

cc_library(
    name = "scripted_transports",
    testonly = True,
    hdrs = [
        "scripted_can_transport.h",
        "scripted_kline_transport.h",
        "scripted_ssm_transport.h",
    ],
    deps = ["//src/backend/protocol"],
)
