load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gtest_targets.bzl", "fastecu_portable_gtest")

package(default_visibility = [
    "//bazel/layers:algorithms_and_above",
    "//bazel/layers:apps_bench",
])

cc_library(
    name = "protocol",
    hdrs = [
        "bytes.h",
        "bytes_compose.h",
        "fixed_buffer.h",
    ],
)

fastecu_portable_gtest(
    name = "bytes_test",
    srcs = ["bytes_test.cpp"],
    deps = [":protocol"],
)

fastecu_portable_gtest(
    name = "fixed_buffer_test",
    srcs = ["fixed_buffer_test.cpp"],
    deps = [":protocol"],
)

fastecu_portable_gtest(
    name = "bytes_compose_test",
    srcs = ["bytes_compose_test.cpp"],
    deps = [":protocol"],
)
