#include "src/platform/desktop/common/serial/remote/remote_serial_backend.h"

#include <QThread>
#include <QWebSocket>
#include <utility>
#include "src/platform/desktop/common/serial/qtrohelper.hpp"
#include "rep_serial_port_actions_replica.h"

RemoteSerialBackend::RemoteSerialBackend(QString peer_address, QString password, QWebSocket *external_socket,
                                         QObject *parent)
    : QObject{parent}, peer_address_(std::move(peer_address)), password_(std::move(password))
{
    if (external_socket && external_socket->thread() != thread())
    {
        emit logW("RemoteSerialBackend: external websocket has foreign thread "
                  "affinity, creating own socket instead",
                  true, true);
        external_socket = nullptr;
    }
    web_socket_ = external_socket ? external_socket : new QWebSocket("", QWebSocketProtocol::VersionLatest, this);
    socket_ = new WebSocketIoDevice(web_socket_, web_socket_);
    StartRemote();
}

RemoteSerialBackend::~RemoteSerialBackend()
{
}

void RemoteSerialBackend::WaitForSource()
{
    while (!serial_remote_->waitForSource(10000))
    {
        SendAutoDiscoveryMessage();
        QThread::msleep(50);
        emit logD("RemoteSerialBackend: Waiting for remote peer...", true, true);
    }
}

void RemoteSerialBackend::StartRemote()
{
    if (peer_address_.startsWith("local:"))
    {
        StartLocal();
    }
    else
    {
        StartOverNetwork();
    }
    QObject::connect(serial_remote_, &SerialPortActionsRemoteReplica::stateChanged, this,
                     &RemoteSerialBackend::serialRemoteStateChanged);
}

void RemoteSerialBackend::StartOverNetwork()
{
    QSslConfiguration ssl_configuration;
    ssl_configuration.setPeerVerifyMode(QSslSocket::VerifyNone);
    web_socket_->setSslConfiguration(ssl_configuration);
    // Start node when Web Socket will be up
    QObject::connect(web_socket_, &QWebSocket::connected, this, &RemoteSerialBackend::websocketConnected);
    node_.setHeartbeatInterval(heartbeat_interval_);
    QObject::connect(web_socket_, &QWebSocket::errorOccurred, this,
                     [this](QAbstractSocket::SocketError error)
                     {
                         emit logD(QString(this->metaObject()->className()) + " startOverNetwork QWebSocket error: " +
                                       QMetaEnum::fromType<QAbstractSocket::SocketError>().valueToKey(error),
                                   true, true);
                     });
    // WebSocket over SSL
    QUrl url("wss://" + peer_address_);
    url.setPath(wss_path_);
    QNetworkRequest req;
    req.setRawHeader(web_socket_password_header_.toUtf8(), password_.toUtf8());
    req.setUrl(url);
    web_socket_->open(req);

    // Connect to source published with name
    // Class SerialPortActionsRemoteReplica is autogenerated from serial_port_actions.rep
    serial_remote_ = node_.acquire<SerialPortActionsRemoteReplica>(remote_object_name_);
    // Don't wait for replication here, it should be done from outside
}

void RemoteSerialBackend::StartLocal()
{
    node_.connectToNode(QUrl(peer_address_));
    serial_remote_ = node_.acquire<SerialPortActionsRemoteReplica>(remote_object_name_);
}

void RemoteSerialBackend::SendAutoDiscoveryMessage()
{
    if (web_socket_->isValid())
    {
        web_socket_->sendTextMessage(autodiscovery_message_);
    }
}

void RemoteSerialBackend::websocketConnected()
{
    // Run client node after socket is up
    node_.addClientSideConnection(socket_);
    SendAutoDiscoveryMessage();
}

void RemoteSerialBackend::serialRemoteStateChanged(QRemoteObjectReplica::State state,
                                                   QRemoteObjectReplica::State old_state)
{
    emit stateChanged(state, old_state);
    if (state == QRemoteObjectReplica::Valid)
    {
        emit logD("RemoteSerialBackend remote connection established", true, true);
    }
    else if (old_state == QRemoteObjectReplica::Valid)
    {
        emit logD("RemoteSerialBackend remote connection lost", true, true);
    }
}

// -- config get/set pairs (44) ------------------------------------------

bool RemoteSerialBackend::GetSerialPortAvailable()
{
    return qtrohelper::SlotSync(serial_remote_->get_serialPortAvailable());
}
bool RemoteSerialBackend::SetSerialPortAvailable(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serialPortAvailable(value));
}
bool RemoteSerialBackend::GetSetRequestToSend()
{
    return qtrohelper::SlotSync(serial_remote_->get_setRequestToSend());
}
bool RemoteSerialBackend::SetSetRequestToSend(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_setRequestToSend(value));
}
bool RemoteSerialBackend::GetSetDataTerminalReady()
{
    return qtrohelper::SlotSync(serial_remote_->get_setDataTerminalReady());
}
bool RemoteSerialBackend::SetSetDataTerminalReady(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_setDataTerminalReady(value));
}

bool RemoteSerialBackend::GetAddSsmHeader()
{
    return qtrohelper::SlotSync(serial_remote_->get_add_ssm_header());
}
bool RemoteSerialBackend::SetAddSsmHeader(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_add_ssm_header(value));
}

bool RemoteSerialBackend::GetAddIso9141Header()
{
    return qtrohelper::SlotSync(serial_remote_->get_add_iso9141_header());
}
bool RemoteSerialBackend::SetAddIso9141Header(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_add_iso9141_header(value));
}

bool RemoteSerialBackend::GetAddIso14230Header()
{
    return qtrohelper::SlotSync(serial_remote_->get_add_iso14230_header());
}
bool RemoteSerialBackend::SetAddIso14230Header(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_add_iso14230_header(value));
}
bool RemoteSerialBackend::GetIsIso14230Connection()
{
    return qtrohelper::SlotSync(serial_remote_->get_is_iso14230_connection());
}
bool RemoteSerialBackend::SetIsIso14230Connection(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_is_iso14230_connection(value));
}
bool RemoteSerialBackend::GetIsCanConnection()
{
    return qtrohelper::SlotSync(serial_remote_->get_is_can_connection());
}
bool RemoteSerialBackend::SetIsCanConnection(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_is_can_connection(value));
}
bool RemoteSerialBackend::GetIsIso15765Connection()
{
    return qtrohelper::SlotSync(serial_remote_->get_is_iso15765_connection());
}
bool RemoteSerialBackend::SetIsIso15765Connection(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_is_iso15765_connection(value));
}
bool RemoteSerialBackend::GetIs29BitId()
{
    return qtrohelper::SlotSync(serial_remote_->get_is_29_bit_id());
}
bool RemoteSerialBackend::SetIs29BitId(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_is_29_bit_id(value));
}

bool RemoteSerialBackend::GetUseOpenport2Adapter()
{
    return qtrohelper::SlotSync(serial_remote_->get_use_openport2_adapter());
}
bool RemoteSerialBackend::SetUseOpenport2Adapter(bool value)
{
    return qtrohelper::SlotSync(serial_remote_->set_use_openport2_adapter(value));
}

int RemoteSerialBackend::GetRequestToSendEnabled()
{
    return qtrohelper::SlotSync(serial_remote_->get_requestToSendEnabled());
}
bool RemoteSerialBackend::SetRequestToSendEnabled(int value)
{
    return qtrohelper::SlotSync(serial_remote_->set_requestToSendEnabled(value));
}
int RemoteSerialBackend::GetRequestToSendDisabled()
{
    return qtrohelper::SlotSync(serial_remote_->get_requestToSendDisabled());
}
bool RemoteSerialBackend::SetRequestToSendDisabled(int value)
{
    return qtrohelper::SlotSync(serial_remote_->set_requestToSendDisabled(value));
}
int RemoteSerialBackend::GetDataTerminalEnabled()
{
    return qtrohelper::SlotSync(serial_remote_->get_dataTerminalEnabled());
}
bool RemoteSerialBackend::SetDataTerminalEnabled(int value)
{
    return qtrohelper::SlotSync(serial_remote_->set_dataTerminalEnabled(value));
}
int RemoteSerialBackend::GetDataTerminalDisabled()
{
    return qtrohelper::SlotSync(serial_remote_->get_dataTerminalDisabled());
}
bool RemoteSerialBackend::SetDataTerminalDisabled(int value)
{
    return qtrohelper::SlotSync(serial_remote_->set_dataTerminalDisabled(value));
}

uint8_t RemoteSerialBackend::GetKlineStartbyte()
{
    return qtrohelper::SlotSync(serial_remote_->get_kline_startbyte());
}
bool RemoteSerialBackend::SetKlineStartbyte(uint8_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_kline_startbyte(value));
}
uint8_t RemoteSerialBackend::GetKlineTesterId()
{
    return qtrohelper::SlotSync(serial_remote_->get_kline_tester_id());
}
bool RemoteSerialBackend::SetKlineTesterId(uint8_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_kline_tester_id(value));
}
uint8_t RemoteSerialBackend::GetKlineTargetId()
{
    return qtrohelper::SlotSync(serial_remote_->get_kline_target_id());
}
bool RemoteSerialBackend::SetKlineTargetId(uint8_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_kline_target_id(value));
}

QByteArray RemoteSerialBackend::GetSsmReceiveHeaderStart()
{
    return qtrohelper::SlotSync(serial_remote_->get_ssm_receive_header_start());
}
bool RemoteSerialBackend::SetSsmReceiveHeaderStart(QByteArray value)
{
    return qtrohelper::SlotSync(serial_remote_->set_ssm_receive_header_start(value));
}

QStringList RemoteSerialBackend::GetSerialPortList()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_list());
}
bool RemoteSerialBackend::SetSerialPortList(QStringList value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_list(value));
}
QString RemoteSerialBackend::GetOpenedSerialPort()
{
    return qtrohelper::SlotSync(serial_remote_->get_openedSerialPort());
}
bool RemoteSerialBackend::SetOpenedSerialPort(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_openedSerialPort(value));
}
QString RemoteSerialBackend::GetSubaru0216bitBootloaderBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_02_16bit_bootloader_baudrate());
}
bool RemoteSerialBackend::SetSubaru0216bitBootloaderBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_02_16bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0416bitBootloaderBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_04_16bit_bootloader_baudrate());
}
bool RemoteSerialBackend::SetSubaru0416bitBootloaderBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_04_16bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0232bitBootloaderBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_02_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::SetSubaru0232bitBootloaderBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_02_32bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0432bitBootloaderBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_04_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::SetSubaru0432bitBootloaderBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_04_32bit_bootloader_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0532bitBootloaderBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_05_32bit_bootloader_baudrate());
}
bool RemoteSerialBackend::SetSubaru0532bitBootloaderBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_05_32bit_bootloader_baudrate(value));
}

QString RemoteSerialBackend::GetSubaru0216bitKernelBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_02_16bit_kernel_baudrate());
}
bool RemoteSerialBackend::SetSubaru0216bitKernelBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_02_16bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0416bitKernelBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_04_16bit_kernel_baudrate());
}
bool RemoteSerialBackend::SetSubaru0416bitKernelBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_04_16bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0232bitKernelBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_02_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::SetSubaru0232bitKernelBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_02_32bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0432bitKernelBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_04_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::SetSubaru0432bitKernelBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_04_32bit_kernel_baudrate(value));
}
QString RemoteSerialBackend::GetSubaru0532bitKernelBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_subaru_05_32bit_kernel_baudrate());
}
bool RemoteSerialBackend::SetSubaru0532bitKernelBaudrate(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_subaru_05_32bit_kernel_baudrate(value));
}

QString RemoteSerialBackend::GetCanSpeed()
{
    return qtrohelper::SlotSync(serial_remote_->get_can_speed());
}
bool RemoteSerialBackend::SetCanSpeed(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_can_speed(value));
}
uint8_t RemoteSerialBackend::GetSerialPortParity()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_parity());
}
bool RemoteSerialBackend::SetSerialPortParity(uint8_t parity)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_parity(parity));
}
QString RemoteSerialBackend::GetSerialPortBaudrate()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_baudrate());
}
bool RemoteSerialBackend::SetSerialPortBaudrate(QString value)
{
    emit logD("Setting serialport baudrate in RemoteSerialBackend", true, true);
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_baudrate(value));
}
QString RemoteSerialBackend::GetSerialPortLinux()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_linux());
}
bool RemoteSerialBackend::SetSerialPortLinux(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_linux(value));
}
QString RemoteSerialBackend::GetSerialPortWindows()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_windows());
}
bool RemoteSerialBackend::SetSerialPortWindows(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_windows(value));
}
QString RemoteSerialBackend::GetSerialPort()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port());
}
bool RemoteSerialBackend::SetSerialPort(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port(value));
}
QString RemoteSerialBackend::GetSerialPortPrefix()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_prefix());
}
bool RemoteSerialBackend::SetSerialPortPrefix(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_prefix(value));
}
QString RemoteSerialBackend::GetSerialPortPrefixLinux()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_prefix_linux());
}
bool RemoteSerialBackend::SetSerialPortPrefixLinux(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_prefix_linux(value));
}
QString RemoteSerialBackend::GetSerialPortPrefixWin()
{
    return qtrohelper::SlotSync(serial_remote_->get_serial_port_prefix_win());
}
bool RemoteSerialBackend::SetSerialPortPrefixWin(QString value)
{
    return qtrohelper::SlotSync(serial_remote_->set_serial_port_prefix_win(value));
}

uint32_t RemoteSerialBackend::GetCanSourceAddress()
{
    return qtrohelper::SlotSync(serial_remote_->get_can_source_address());
}
bool RemoteSerialBackend::SetCanSourceAddress(uint32_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_can_source_address(value));
}
uint32_t RemoteSerialBackend::GetCanDestinationAddress()
{
    return qtrohelper::SlotSync(serial_remote_->get_can_destination_address());
}
bool RemoteSerialBackend::SetCanDestinationAddress(uint32_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_can_destination_address(value));
}
uint32_t RemoteSerialBackend::GetIso15765SourceAddress()
{
    return qtrohelper::SlotSync(serial_remote_->get_iso15765_source_address());
}
bool RemoteSerialBackend::SetIso15765SourceAddress(uint32_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_iso15765_source_address(value));
}
uint32_t RemoteSerialBackend::GetIso15765DestinationAddress()
{
    return qtrohelper::SlotSync(serial_remote_->get_iso15765_destination_address());
}
bool RemoteSerialBackend::SetIso15765DestinationAddress(uint32_t value)
{
    return qtrohelper::SlotSync(serial_remote_->set_iso15765_destination_address(value));
}

// -- operations -----------------------------------------------------------

bool RemoteSerialBackend::IsSerialPortOpen()
{
    return qtrohelper::SlotSync(serial_remote_->is_serial_port_open());
}

int RemoteSerialBackend::ChangePortSpeed(QString port_speed)
{
    return qtrohelper::SlotSync(serial_remote_->change_port_speed(port_speed));
}

// NOTE: pinned quirk, preserved verbatim from the old facade (serial_port_actions.cpp
// set_kline_timings, lines 885-891): the remote branch never forwarded this call to
// serial_remote at all (only the direct branch did anything), and the facade always
// returned STATUS_SUCCESS (true) regardless. Not a bug this task is chartered to fix.
bool RemoteSerialBackend::SetKlineTimings(uint32_t parameter, int value)
{
    Q_UNUSED(parameter);
    Q_UNUSED(value);
    return true;
}

int RemoteSerialBackend::SetJ2534Ioctl(uint32_t parameter, int value)
{
    return qtrohelper::SlotSync(serial_remote_->set_j2534_ioctl(parameter, value));
}

QByteArray RemoteSerialBackend::FiveBaudInit(QByteArray output)
{
    return qtrohelper::SlotSync(serial_remote_->five_baud_init(output));
}

int RemoteSerialBackend::FastInit(QByteArray output)
{
    return qtrohelper::SlotSync(serial_remote_->fast_init(output));
}

int RemoteSerialBackend::SetLecLines(int lec1, int lec2)
{
    return qtrohelper::SlotSync(serial_remote_->set_lec_lines(lec1, lec2));
}

int RemoteSerialBackend::PulseLec1Line(int timeout)
{
    return qtrohelper::SlotSync(serial_remote_->pulse_lec_1_line(timeout));
}

int RemoteSerialBackend::PulseLec2Line(int timeout)
{
    return qtrohelper::SlotSync(serial_remote_->pulse_lec_2_line(timeout));
}

void RemoteSerialBackend::ResetConnection()
{
    qtrohelper::SlotSync(serial_remote_->reset_connection()); // bool result discarded
}

// NOTE: pinned quirk, preserved verbatim from the old facade (serial_port_actions.cpp
// read_serial_obd_data, lines 1005-1016): the remote branch was never populated in the
// original if/else — only the facade's former direct-connection branch called through and logged a
// response; the remote path fell through and returned a default-constructed (empty)
// QByteArray without ever calling serial_remote. The .rep does expose this slot
// (SerialPortActionsRemoteReplica::read_serial_obd_data), so this looks like an
// omission in the old code rather than an intentional no-op, but this task's mandate
// is a mechanical, behavior-preserving move -- not a bugfix -- so the omission is
// pinned here rather than "fixed" by wiring in the call.
QByteArray RemoteSerialBackend::ReadSerialObdData(uint16_t timeout)
{
    Q_UNUSED(timeout);
    return QByteArray();
}

QByteArray RemoteSerialBackend::ReadSerialData(uint16_t timeout)
{
    return qtrohelper::SlotSync(serial_remote_->read_serial_data(timeout));
}

QByteArray RemoteSerialBackend::WriteSerialData(QByteArray output)
{
    return qtrohelper::SlotSync(serial_remote_->write_serial_data(output));
}

QByteArray RemoteSerialBackend::WriteSerialDataEchoCheck(QByteArray output)
{
    return qtrohelper::SlotSync(serial_remote_->write_serial_data_echo_check(output));
}

// NOTE: pinned quirk, preserved from the old facade (serial_port_actions.cpp
// get_is_tx_done, lines 1069-1075): the remote branch was commented out, so the old
// non-void function fell off the end on the remote path -- undefined behavior. There
// is no safe value to "recover" from the original, so this pins a safe default: report
// tx done so callers relying on this to gate further sends don't spin/deadlock.
bool RemoteSerialBackend::GetIsTxDone()
{
    return true;
}

int RemoteSerialBackend::ClearRxBuffer()
{
    return qtrohelper::SlotSync(serial_remote_->clear_rx_buffer());
}

int RemoteSerialBackend::ClearTxBuffer()
{
    return qtrohelper::SlotSync(serial_remote_->clear_tx_buffer());
}

int RemoteSerialBackend::SendPeriodicJ2534Data(QByteArray output, int timeout)
{
    return qtrohelper::SlotSync(serial_remote_->send_periodic_j2534_data(output, timeout));
}

int RemoteSerialBackend::StopPeriodicJ2534Data()
{
    return qtrohelper::SlotSync(serial_remote_->stop_periodic_j2534_data());
}

QStringList RemoteSerialBackend::CheckSerialPorts()
{
    return qtrohelper::SlotSync(serial_remote_->check_serial_ports());
}

QString RemoteSerialBackend::OpenSerialPort()
{
    return qtrohelper::SlotSync(serial_remote_->open_serial_port());
}

unsigned long RemoteSerialBackend::ReadVbatt()
{
    return qtrohelper::SlotSync(serial_remote_->read_vbatt());
}
