load("//bazel:qt_targets.bzl", "QT_DEPS", "qt_cc_library")

package(default_visibility = [
    "//bazel/layers:src",
    "//bazel/layers:tests",
])

qt_cc_library(
    name = "mock_openport",
    testonly = True,
    srcs = [],
    hdrs = ["mock_openport.h"],
    target_compatible_with = select({
        "@platforms//os:windows": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = QT_DEPS + ["//src/platform/desktop/unix/j2534"],
)
