# gazelle:map_kind cc_library qt_cc_library //bazel:qt_targets.bzl
load("//bazel:qt_targets.bzl", "qt_cc_library")

package(default_visibility = [
    "//bazel/layers:src",
    "//bazel/layers:tests",
])

qt_cc_library(
    name = "mock_openport",
    testonly = True,
    # Required by the header-only moc macro.
    hdrs = ["mock_openport.h"],
    target_compatible_with = select({
        "@platforms//os:windows": ["@platforms//:incompatible"],
        "//conditions:default": [],
    }),
    deps = ["//bazel/qt:core"],
)
