load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel:gtest_targets.bzl", "fastecu_portable_gtest")

package(default_visibility = ["//bazel/layers:algorithms_and_above"])

cc_library(
    name = "address",
    hdrs = ["address.h"],
)

fastecu_portable_gtest(
    name = "address_test",
    srcs = ["address_test.cpp"],
    deps = [
        ":address",
        "@googletest//:gtest",
    ],
)
